services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vitis_net
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - vitis_net

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:admin@db:5432/crm
    ports:
      - "8000:8000"
    networks:
      - vitis_net

  # frontend:
  #   build: ./frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - vitis_net

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #   networks:
  #     - vitis_net

volumes:
  postgres_data:

networks:
  vitis_net:
    driver: bridge