services:
  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    networks:
      - vitis_net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=ofabioacarvalho@gmail.com
      - PGADMIN_DEFAULT_USER=postgres
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
      - ./backup:/var/lib/pgadmin/storage
    depends_on:
      - db
    networks:
      - vitis_net

  back:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      DATABASE_NAME: vitis
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - vitis_net
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            python manage.py runserver 0.0.0.0:8000"

  # front:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #   command: >
  #     sh -c "npm i &&
  #           npm run dev -- --host=0.0.0.0 --port=3000"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - back
  #   networks:
  #     - vitis_net

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #   networks:
  #     - vitis_net

  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"
    networks:
      - vitis_net

  # worker:
  #   build: .
  #   container_name: celery_worker
  #   command: sh -c "sleep 10 && celery -A celery_worker.celery worker --loglevel=info"
  #   depends_on:
  #     - redis
  #   networks:
  #     - vitis_net

volumes:
  postgres_data:

networks:
  vitis_net:
    driver: bridge