# Generated by Django 4.2.19 on 2025-03-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_stage_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
