# Generated by Django 4.2.19 on 2025-03-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_auditlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
