# Generated by Django 4.2.19 on 2025-03-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=14, null=True, unique=True),
                ),
                ("phone", models.CharField(max_length=11)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("cep", models.CharField(blank=True, max_length=8, null=True)),
                ("code", models.CharField(blank=True, max_length=25, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="company")),
                ("message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "company",
                "ordering": ["name"],
            },
        ),
    ]
